# -*- coding: utf-8 -*-
"""Ecommerce_Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQJK-BwoTK0nCvZ9PB27CjboTX3yLTTv
"""

import pandas as pd
import random

random.seed(42)

# Define data parameters
regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

# Generate 200 sales transactions
data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

df = pd.DataFrame(data)
print(df.head(10))
print(f"\nDataset shape: {df.shape}")

"""## Task 1: Basic Grouping and Single Aggregations

1.1.Total sales per region (sorted descending)
"""

regional_sales = (
    df.groupby('region')['sales_amount']   # group rows by region
    .sum()                                  # sum sales_amount within each group
    .reset_index()                          # convert Series index → column
)
regional_sales.columns = ['region', 'total_sales']
regional_sales = regional_sales.sort_values('total_sales', ascending=False)

print(regional_sales)

"""1.2: Transaction count per category"""

category_counts = (
    df.groupby('category')['transaction_id']  # group by category
    .count()                                   # count non-null rows per group
    .reset_index()                             # flatten to DataFrame
)
category_counts.columns = ['category', 'transaction_count']
category_counts = category_counts.sort_values('transaction_count', ascending=False)

print(category_counts)

"""1.3: Average sales per salesperson"""

salesperson_avg = (
    df.groupby('salesperson')['sales_amount']  # group by salesperson
    .mean()                                     # mean of sales_amount per group
    .reset_index()                              # flatten to DataFrame
)
salesperson_avg.columns = ['salesperson', 'avg_sales']
salesperson_avg['avg_sales'] = salesperson_avg['avg_sales'].round(2)
salesperson_avg = salesperson_avg.sort_values('avg_sales', ascending=False)

print(salesperson_avg)

"""1.4: For each result, use reset_index() to convert the result into a clean DataFrame"""

# --- BEFORE reset_index() ---
before = df.groupby('region')['sales_amount'].sum()

print(type(before))          # <class 'pandas.Series'>
print(before)
print("-"*40)
print(before.index.tolist())

# --- AFTER reset_index() ---
after = df.groupby('region')['sales_amount'].sum().reset_index()

print(type(after))           # <class 'pandas.DataFrame'>
print(after)
print("-"*40)
print(after.columns.tolist())
print("-"*40)
print(after.index.tolist())

"""1.4..1.Regional total sales"""

# --- Applied to all three groupby results ---
print("-"*40)
print("--- 1. Regional total sales ---");
print("-"*40)
# 1. Regional total sales
regional_sales = df.groupby('region')['sales_amount'].sum().reset_index()
regional_sales.columns = ['region', 'total_sales']
regional_sales['total_sales'] = regional_sales['total_sales'].round(2)
print(regional_sales)

"""1.4.2.Category transaction counts"""

print("-"*40)
print("--- 2. Category transaction counts ---");
print("-"*40)
# 2. Category transaction counts
category_counts = df.groupby('category')['transaction_id'].count().reset_index()
category_counts.columns = ['category', 'transaction_count']
print(category_counts)

"""1.4.3.Salesperson average sales"""

print("-"*40)
print("--- 3. Salesperson average sales ---");
print("-"*40)
# 3. Salesperson average sales
salesperson_avg = df.groupby('salesperson')['sales_amount'].mean().reset_index()
salesperson_avg.columns = ['salesperson', 'avg_sales']
salesperson_avg['avg_sales'] = salesperson_avg['avg_sales'].round(2)
print(salesperson_avg)
print("-"*40)

"""1.5: Sort the regional sales results in descending order using sort_values(ascending=False) to identify the top-performing region"""

# --- Build regional sales DataFrame ---
regional_sales = df.groupby('region')['sales_amount'].sum().reset_index()
regional_sales.columns = ['region', 'total_sales']
regional_sales['total_sales'] = regional_sales['total_sales'].round(2)

# --- BEFORE sort_values() — alphabetical order (default) ---
print("-"*50)
print(" BEFORE sort_values() - alphabetical order (default)");
print("-"*50)
print(regional_sales)

# --- ascending=True — lowest sales first ---
print("-"*50)
print(" ascending=True - lowest sales first");
print("-"*50)
print(regional_sales.sort_values('total_sales', ascending=True))

# --- ascending=False — highest sales first ---
print("-"*50)
print("  ascending=False - highest sales first ");
print("-"*50)
descending = regional_sales.sort_values('total_sales', ascending=False)
print(descending)

# --- Identify top-performing region ---
print("-"*50)
print(" Identify top-performing region");
print("-"*50)
top_region = descending.iloc[0]           # first row = highest value
print(f"Top region : {top_region['region']}")         # South
print(f"Total sales: ${top_region['total_sales']:,.2f}")  # $158,977.36

# --- Full ranking with gap vs top ---
print("-"*50)
print(" Full ranking with gap vs top");
print("-"*50)
ranked = descending.reset_index(drop=True)   # clean 0-based index after sort
print(ranked)

"""## Task 2: Multi-Column Grouping and Multiple Aggregations

2.1.Task 1: Multi-column groupby
"""

# --- Task 1: Multi-column groupby ---
region_category = (
    df.groupby(['region', 'category'])['sales_amount']
    .sum()
    .reset_index()
)
region_category.columns = ['region', 'category', 'total_sales']
print("-"*60)
print(" Task 1: Multi-column groupby");
print("-"*60)
print(region_category)

"""2.2: agg() — three metrics in one call"""

# --- Task 2: agg() — three metrics in one call ---
salesperson_metrics = (
    df.groupby('salesperson')['sales_amount']
    .agg(['sum', 'mean', 'count'])
    .reset_index()
)
salesperson_metrics.columns = ['salesperson', 'total_sales', 'avg_sales', 'transaction_count']
salesperson_metrics['total_sales'] = salesperson_metrics['total_sales'].round(2)
salesperson_metrics['avg_sales']   = salesperson_metrics['avg_sales'].round(2)
print("-"*60)
print(" Task 2: agg() - three metrics in one call");
print("-"*60)
print(salesperson_metrics)

"""2.3: Sort by total_sales descending"""

# --- Task 3: Sort by total_sales descending ---
salesperson_sorted = (
    salesperson_metrics
    .sort_values('total_sales', ascending=False)
    .reset_index(drop=True)
)
print("-"*60)
print(" Task 3: Sort by total_sales descendingl");
print("-"*60)
print(salesperson_sorted)
print("-"*60)
top = salesperson_sorted.iloc[0]
print(top)

"""2.4: idxmax() — find the category label with max revenue"""

# --- Task 4: idxmax() — find the category label with max revenue ---
category_sales = df.groupby('category')['sales_amount'].sum()
print("-"*60)
print(" Task 4: idxmax() — find the category label with max revenue ");
print("-"*60)
print(category_sales)
print("-"*60)
max_category = category_sales.idxmax()
print(f" Max category : {max_category}")
print(f" Revenue      : ${category_sales[max_category]:,.2f}")

"""## Task 3: Custom Aggregation and Complete Sales Report

3.1 - Define the custom function
"""

def sales_range(x):
    return x.max() - x.min()

"""3.2 - Mix custom + standard aggregations"""

region_custom = (
    df.groupby('region')['sales_amount']
    .agg(['sum', 'mean', 'min', 'max', sales_range])  # strings + function object
    .reset_index()
)
region_custom.columns = ['region', 'total_sales', 'avg_sales',
                          'min_sale', 'max_sale', 'sales_range']

print( "-" * 70)
print("  Task 2 - Region aggregation with custom sales_range")
print( "-" * 70)
print(region_custom.to_string(index=False))

"""3.3 - Final summary report using dict agg()"""

# --- Step 1: Build the raw multi-level result ---
summary_raw = (
    df.groupby('region').agg({
        'sales_amount': ['sum', 'mean'],  # two functions on one column
        'customer_id':  'count'           # one function on a different column
    })
    .reset_index()
)

print( "\n"+"-" * 70)
print("  1. RAW output (multi-level column header)")
print( "-" * 70)
print("  Column tuples:", summary_raw.columns.tolist())

print(summary_raw.to_string(index=False))

# --- Step 2: Flatten to a clean single-level DataFrame ---
summary_raw.columns = ['region', 'total_sales', 'avg_sales', 'transaction_count']
summary = summary_raw.sort_values('total_sales', ascending=False).reset_index(drop=True)
print( "\n"+"-" * 70)
print("2. CLEAN summary report (after flattening columns)")
print( "-" * 70)
print(summary.to_string(index=False))

# --- Step 3: Formatted report output ---
print("\n"+"-" * 70)
print("3. Regional Sales Summary Report")
print("-" * 70)
print(f"  {'Rank':<6}{'Region':<10}{'Transactions':>14}{'Total Sales':>14}{'Avg / Deal':>12}")
print("-" * 70)
for i, row in summary.iterrows():
    print(
        f"  #{i+1:<5}{row['region']:<10}"
        f"{row['transaction_count']:>14,}"
        f"{row['total_sales']:>14,.2f}"
        f"{row['avg_sales']:>12,.2f}"
    )
print("-" * 70)
print(
    f"  {'TOT':<6}{'ALL':<10}"
    f"{summary['transaction_count'].sum():>14,}"
    f"{summary['total_sales'].sum():>14,.2f}"
)

"""3.4 - Multi-level column structure explained"""

raw = (
    df.groupby('region').agg({
        'sales_amount': ['sum', 'mean'],
        'customer_id':  'count'
    }).reset_index()
)

print("\n" + "-" * 70)
print("4. Three column-flattening methods")
print("-" * 70)
print("  Original columns:", raw.columns.tolist())
print("\n" + "-" * 70)

# Method 1 - Direct rename (recommended: full control over names)
m1 = raw.copy()
m1.columns = ['region', 'total_sales', 'avg_sales', 'transaction_count']
print("Method 1 - direct rename:")
#print(" ", m1.columns.tolist())
print(m1.to_string(index=False))
print("\n" + "-" * 70)

# Method 2 - Auto-join with underscore separator
m2 = raw.copy()
m2.columns = ['_'.join(col).strip('_') for col in m2.columns.values]
print("Method 2 - underscore join:")
#print(" ", m2.columns.tolist())
print(m2.to_string(index=False))

print("\n" + "-" * 70)
# Method 3 - f-string conditional (skips '_' when level-1 is empty)
m3 = raw.copy()
m3.columns = [f"{a}_{b}" if b else a for a, b in m3.columns]
print("Method 3 - f-string conditional:")
#print(" ", m3.columns.tolist())
print(m3.to_string(index=False))
print("\n" + "-" * 70)

# Accessing columns BEFORE flattening (using tuple keys)
raw2 = df.groupby('region').agg({
    'sales_amount': ['sum', 'mean'],
    'customer_id':  'count'
})

print(raw2)

print( "\n"+"-" * 70)
print("Accessing multi-level columns with tuple keys:")
print( "-" * 70)
print(raw2[('sales_amount', 'sum')])        # one sub-column
print( "\n"+"-" * 70)
print("Selecting all sales_amount sub-columns:")
print( "-" * 70)
print(raw2['sales_amount'])                 # returns both sum and mean
print( "-" * 70)

"""SUMMARY: When do you get multi-level columns?

    .agg(['sum','mean']) on ONE column -- flat (single-level)
    .agg({'col1':['sum','mean'], -- MultiIndex (two-level)
    'col2':'count'}) -- must flatten before rename
"""