# -*- coding: utf-8 -*-
"""Question1_Pandas_DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMazXm7qp9lEmdFNBOGyEK4FbodrVpip
"""

import pandas as pd

# Step 1: Create the student DataFrame
data = {
    'StudentID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah', 'Ivan', 'Julia'],
    'Age': [20, 21, 19, 22, 20, 21, 23, 19, 22, 20],
    'Marks': [88, 75, 92, 65, 78, 85, 70, 95, 60, 80],
    'Grade': ['A', 'B', 'A', 'C', 'B', 'A', 'B', 'A', 'C', 'B']
}

df = pd.DataFrame(data)
print("DataFrame created successfully!")
print(df)

"""Step 2: Save the DataFrame as a CSV file"""

df.to_csv('students.csv', index=False)
print("\nDataFrame saved to students.csv")

"""Step 3: Reload students.csv into a new DataFrame"""

df = pd.read_csv('students.csv')
print("\nCSV reloaded successfully!")

"""Step 4: Display the first 3 rows"""

print("\nFirst 3 rows (df.head(3)):")
print(df.head(3))

"""Step 5: Display the statistical summary"""

print("\nStatistical Summary (df.describe()):")
print(df.describe())

"""Step 6: Explore the DataFrame further"""

print("\nShape of DataFrame (df.shape):")
print(df.shape)

"""Display Data Type"""

print("\nData Types (df.dtypes):")
print(df.dtypes)

"""Display DataFrame info"""

print("\nDataFrame Info (df.info()):")
df.info()