# -*- coding: utf-8 -*-
"""intermediate_sql_query.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X52on2kbbfXOh5ttGTOCFeyNUrskDIgR

# Intermediate SQL Querying

Load both CSVs into a SQLite database using pandas and sqlite3
"""

# Public dataset URLs
import pandas as pd
import sqlite3

customers_url = "https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/customers.csv"
orders_url = "https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/orders.csv"

# Read CSVs
customers_df = pd.read_csv(customers_url)
orders_df = pd.read_csv(orders_url)

# Load into in-memory SQLite
conn = sqlite3.connect(":memory:")
customers_df.to_sql("customers", conn, index=False, if_exists="replace")
orders_df.to_sql("orders", conn, index=False, if_exists="replace")

# Quick sanity checks
print(f"customers table : {len(customers_df):>4} rows  |  columns: {list(customers_df.columns)}")
print(f"orders    table : {len(orders_df):>4} rows  |  columns: {list(orders_df.columns)}")

"""## Task 1 - Aggregation and Grouping

Using **only** the `orders` table, retrieve each customer's:
- total number of orders (`order_count`)
- total freight (`total_freight`)
- average freight per order (`avg_freight`)

Sorted by `total_freight` descending; top 10 rows displayed.
"""

query_task1 = """
SELECT
    CustomerID,
    COUNT(OrderID) AS order_count,
    ROUND(SUM(Freight), 2) AS total_freight,
    ROUND(AVG(Freight), 2) AS avg_freight
FROM orders
GROUP BY CustomerID
ORDER BY total_freight DESC;
"""

task1_df = pd.read_sql_query(query_task1, conn)

print("--- Task 1 - Top 10 Customers by Total Freight ---")
print(task1_df.head(10).to_string(index=False))

"""## Task 2 - WHERE vs. HAVING

Two queries that both reference a freight threshold — but at different stages of query execution.

Query A: From the orders table, filter rows where Freight is greater than 50 before aggregation, then group by CustomerID and return the count of such orders as high_freight_orders
"""

query_A = """
SELECT
    CustomerID,
    COUNT(OrderID) AS high_freight_orders
FROM orders
WHERE Freight > 50
GROUP BY CustomerID
ORDER BY high_freight_orders DESC;
"""

task2a_df = pd.read_sql_query(query_A, conn)

print("--- Query A — WHERE Freight > 50 (row-level filter BEFORE aggregation) ---\n")
print(task2a_df.head(10).to_string(index=False))
print(f"\nCustomers returned: {len(task2a_df)}")

"""Query B: From the orders table, group by CustomerID and return only those customers whose total freight exceeds 500, using HAVING. Return CustomerID and total_freight."""

query_B = """
SELECT
    CustomerID,
    ROUND(SUM(Freight), 2) AS total_freight
FROM orders
GROUP BY CustomerID
HAVING SUM(Freight) > 500
ORDER BY total_freight DESC;
"""

task2b_df = pd.read_sql_query(query_B, conn)

print("--- Query B — HAVING SUM(Freight) > 500 (group-level filter AFTER aggregation) ---\n")
print(task2b_df.to_string(index=False))
print(f"\nCustomers returned: {len(task2b_df)}")

"""### Explanation — WHERE vs. HAVING

`WHERE` and `HAVING` apply their filters at **completely different points** in SQL's logical execution order.  

- **Query A (`WHERE Freight > 50`)** eliminates individual order rows whose freight is ≤ 50 *before* any grouping takes place. The resulting `high_freight_orders` count tells us how many qualifying single orders each customer had — a customer who placed 10 orders of \$40 each would be **excluded entirely**, because no single order clears the threshold.  

- **Query B (`HAVING SUM(Freight) > 500`)** first groups *all* rows by `CustomerID` and sums every order's freight — including small ones — then discards groups whose accumulated total falls below 500. That same customer with 10 × \$40 orders would show a `total_freight` of \$400 and be excluded, but a customer with 15 × \$40 orders (\$600 total) would be **included**, even though no individual order exceeded any threshold.  

In short: `WHERE` is a **row-level pre-filter** that shapes which data enters the aggregation, while `HAVING` is a **group-level post-filter** that shapes which aggregated results are returned.

## Task 3 - JOIN and Aggregation

Join customers and orders to enrich the aggregation with company name and country.
"""

# ---INNER JOIN — only customers who have at least one order ---

query_inner = """
SELECT
    c.CompanyName,
    c.Country,
    COUNT(o.OrderID)        AS order_count,
    ROUND(SUM(o.Freight), 2)  AS total_freight
FROM customers c
INNER JOIN orders o
    ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.CompanyName, c.Country
ORDER BY total_freight DESC;
"""

inner_df = pd.read_sql_query(query_inner, conn)

print("--- INNER JOIN — Customers WITH Orders ---\n")
print(inner_df.head(10).to_string(index=False))
print(f"\nTotal customers returned: {len(inner_df)}")

#  LEFT JOIN — all customers; NULL / 0 for those with no orders
# COALESCE converts NULL freight (unmatched customers) to 0 for readability.

query_left = """
SELECT
    c.CompanyName,
    c.Country,
    COUNT(o.OrderID)                   AS order_count,
    ROUND(COALESCE(SUM(o.Freight), 0), 2) AS total_freight
FROM customers c
LEFT JOIN orders o
    ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.CompanyName, c.Country
ORDER BY total_freight DESC;
"""

left_df = pd.read_sql_query(query_left, conn)

print("--- LEFT JOIN — ALL Customers (including those with no orders) ---\n")
print(left_df.head(10).to_string(index=False))
print(f"\nTotal customers returned: {len(left_df)}")

# --- Identify customers with no orders (the rows INNER JOIN would have dropped) ---
no_orders = left_df[left_df["order_count"] == 0]
print(f"Customers with no orders (LEFT JOIN extras): {len(no_orders)}")
if len(no_orders) > 0:
    print(no_orders.to_string(index=False))

"""### Explanation — INNER JOIN vs. LEFT JOIN

**INNER JOIN** returns only rows where a matching `CustomerID` exists in **both** tables. Any customer in the `customers` table who has never placed an order is silently excluded from the result, because there is no corresponding row in `orders` to pair with.


**LEFT JOIN** keeps *every* row from the **left** table (`customers`) regardless of whether a match exists in `orders`. For customers with no orders, all columns from the `orders` side arrive as `NULL`. `COALESCE(SUM(o.Freight), 0)` converts that NULL to `0` for a cleaner display, and `COUNT(o.OrderID)` naturally returns `0` when there are no matching order rows.


The practical difference is that the LEFT JOIN result set is **larger** — it includes the full customer catalogue — making it the right choice when you need to report on *all* customers and simply want to note that some have no activity, rather than hiding them from the analysis entirely.
"""