# -*- coding: utf-8 -*-
"""Vasanth_Dhandapani_Sensor_Temperature_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1noMGEKOQud4MC870J1VvqQzC7ry_L8Ni
"""

import numpy as np
# Daily Temperature Readings Data
data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

"""Task 1 - Shape and Mean Temperature per Station"""

print("Shape:", data.shape)
mean_per_station = data.mean(axis=1)
print("Mean temperature per station:", mean_per_station)

"""Task 2 - Boolean mask - readings above 28.0°C"""

mask = data > 28.0
above_28 = data[mask]
print("Temperatures above 28.0°C:", above_28)

"""Task 3 - Normalize to [0, 1] range"""

normalized = (data - data.min()) / (data.max() - data.min())
print("Normalized data (rounded to 2 decimal places):")
print(np.round(normalized, 2))